self.is_running object initialized in __init__ method for QueueManager. Every now and then, due to thread scheduling, if QueueManager.get_next_task method is called by WorkerThreadPool.thread_main before QueueManager.start has been called by the pycherry engine, an 'AttributeError: QueueManager instance has no attribute 'is_running'' exception is raised because self.is_running does not exist for QueueManager